collect_data:
  name: Collect Data
  description: Collect data from the Meter Collector.
  fields:
    instance_name:
      description: The instance name of the Meter Collector.
      example: water_meter
      required: true
      selector:
        text:

upload_data:
  name: Upload Data
  description: Upload data from the Meter Collector.
  fields:
    instance_name:
      description: The instance name of the Meter Collector.
      example: water_meter
      required: true
      selector:
        text:
